#!/bin/bash
#
# /etc/rc.d/init.d/tomcatd or /etc/init.d/tomcatd
# init script for kafka precesses
#
# processname: kafkad
# description: kafka is a distributed  streaming platform
# chkconfig: 
# description: Start up the kafka service.

if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ]; then
  . /etc/rc.d/init.d/functions
else
  echo -e "/atomcat: unable to locate functions lib. Cannot continue."
exit -1
fi

RETVAL=$?
USER=whsh
KAFKA_HOME="/home/$USER/kafka"


start(){
  su - ${USER} -c "${KAFKA_HOME}/bin/kafka-server-start.sh ${KAFKA_HOME}/config/server.properties > ${KAFKA_HOME}/logs/kafka_server.log &"
  echo "kafka service is started..."
}
stop(){
  str=`su - ${USER} -c "jps | grep Kafka"`
  #str=${str% *}
  if [[ "x$str" != "x" ]];then   
    su - ${USER} -c "${KAFKA_HOME}/bin/kafka-server-stop.sh"
    #kill -9 $str
    echo "kafka service($str) is killed..."
  else
    echo "kafka servie is not running..."
  fi
}
restart(){
  stop  
  sleep 2
  start
}

status(){
  # su - ${USER} -c "${KAFKA_HOME}/bin/kafka-server-stop.sh"
  str=`su - ${USER} -c "jps | grep Kafka"`
  if [[ "x$str" != "x" ]];then
     echo "kafka($str) is running..."
     return 0
  else
     echo "kafka is down..."
     return 1
  fi
}

case "$1" in
start)
  if [ -f ${KAFKA_HOME}/bin/kafka-server-start.sh ];
  then
  start
  fi
  ;;
stop)
  if [ -f ${KAFKA_HOME}/bin/kafka-server-stop.sh ];
  then
  stop
  fi
  ;;
restart|reload)
  restart
  ;;
status)
  status
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|reload|status}"
  exit 1
  ;;
esac

exit $RETVAL