#!/bin/bash
#
# /etc/rc.d/init.d/kibanad or /etc/init.d/kibanad
# init script for kibana precesses
#
# processname: kibanad
# description: kibana is used for showing search result
# chkconfig: 
# description: Start up the kibana service.

if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ]; then
  . /etc/rc.d/init.d/functions
else
  echo -e "/atomcat: unable to locate functions lib. Cannot continue."
exit -1
fi

RETVAL=$?
USER=lite
KIBANA_HOME="/home/$USER/kibana-5.5.0"

#export JAVA_HOME=/home/lite/jdk1.8.0_131
source /home/$USER/.bash_profile

start(){
  if [ "`whoami`" = "root" ];then
    su - ${USER} -c "nohup sh ${KIBANA_HOME}/bin/kibana >/dev/null 2>&1 &"
    echo "kibana service is started..."
  elif [ "`whoami`" = "lite" ];then
    #chmod 777 ${KIBANA_HOME}/bin/kibana
    eval "nohup ${KIBANA_HOME}/bin/kibana >/dev/null 2>&1 &"
    echo "kibana service is started..."
  else
    echo "please used lite or root"
  fi
}
stop(){
  #str=`su - ${USER} -c "jps | grep LogCollectorMain"`
  #str=${str% *}
  str=`ps aux | grep kibana | grep cli | grep ${USER} | grep -v grep | awk '{print $2}'`
  if [[ "x$str" != "x" ]];then   
    kill -9 $str
    echo "kibana service($str) is killed...."
  else
    echo "kibana servie is not running..."
  fi
}
restart(){
  stop  
  sleep 2
  start
}

status(){
  #str=`su - ${USER} -c "jps | grep LogCollectorMain"`
  str=`ps aux | grep kibana | grep cli | grep ${USER} | grep -v grep | awk '{print $2}'`
  if [[ "x$str" != "x" ]];then
     echo "kibana($str) is running..."
     return 0
  else
     echo "kibana is down..."
     return 1
  fi
}

case "$1" in
start)
  if [ -f ${KIBANA_HOME}/bin/kibana ];
  then
  start
  fi
  ;;
stop)
  if [ -f ${KIBANA_HOME}/bin/kibana ];
  then
  stop
  fi
  ;;
restart|reload)
  restart
  ;;
status)
  status
  ;;
*)
  echo $"Usage: $0 {start|stop|restart|reload|status}"
  exit 1
  ;;
esac

exit $RETVAL
